### ISSUE TITLE
Integrated Terminal Partially Hidden

### ISSUE THREAD

**Issue by ntruessel** [zrax/aur-visual-studio-code-oss#2]
When opening the integrated terminal, the first 3 lines are hidden. This happens only for the `visual-studio-code-oss` package, `visual-studio-code` is not affected.

```
visual-studio-code-oss --version
1.8.1
undefined
```

Installed Plugins:
- C/C++ 0.9.3
- Native Debug 0.16.0
- Rust 0.2.3
- TOML Language Support 0.0.3
- Vim 0.4.10
- vscode-icons 4.3.0

**Comment by zrax** [comment]
I'm not sue what issue you're seeing, since it appears correctly for me.  Can you add a screenshot or something?

**Comment by ntruessel** [comment]
Right after I open it:
![before](https://cloud.githubusercontent.com/assets/12136827/22031484/0480b11e-dce1-11e6-81ca-9127fee2a1e9.png)

After hitting enter once:
![after](https://cloud.githubusercontent.com/assets/12136827/22031490/09e8cc4a-dce1-11e6-9680-ac92ef73eee6.png)

`clear` resets it to the state after opening vscode

**Comment by ntruessel** [comment]
Seems to be unrelated to the used shell and the prompt

**Comment by ntruessel** [comment]
This seems fixed now
